<?php
$z[0]=Array("field","",70,98);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",100,129);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n                <div class=\"list-pro\"><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" alt=\"\"/></a></div>\r\n                ",157,350);
$z[2][4]['flag']="c";
$z[2][4]['row']="1";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("arclist","\r\n                    <a href=\"[field:arcurl/]\">[field:shorttitle/]</a>\r\n                    ",413,561);
$z[3][4]['row']="4";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("field","",592,620);
$z[4][4]['name']="typeurl";

?>