<?php
$z[0]=Array("typeurl","",51,67);
$z[1]=Array("typename","",69,86);
$z[2]=Array("recom","\r\n                global \$dsql;\r\n                \$sql=\"select title from oraimo_archives where flag LIKE '%c%' and typeid=16\";\r\n                \$recom=\$dsql->GetOne(\$sql);\r\n                @me='d';\r\n                ",114,369);
$z[2][4]['runphp']="yes";
$z[3]=Array("id","",387,398);
$z[4]=Array("qupro","-->\r\n                    <!--global \$dsql;-->\r\n                  <!--\$art3=\"select title from oraimo_archives where id=109\";-->\r\n                  <!--\$links=GetOneArchive(109);-->\r\n                  <!--\$url=\$url['arcurl'];-->\r\n                <!--",423,712);
$z[4][4]['runphp']="yes";

?>