<li class="[field:global name=autoindex/]">
                                <h3><a href="{dede:field name='typeurl'/}" >{dede:field name='typename'/}</a></h3>

                                    {dede:channel type='son' row='10' noself='yes'}
                                    <a href='[field:typeurl/]'><span>[field:typename/]</span></a>
                                    {/dede:channel}

                            </li>