<?php
$z[0]=Array("field","",68,96);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",98,127);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n              <div class=\"list-pro\"><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" alt=\"\"/></a></div>              ",153,340);
$z[2][4]['flag']="c";
$z[2][4]['row']="1";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("channel","\r\n              <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n              ",395,529);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";
$z[4]=Array("field","",554,582);
$z[4][4]['name']="typeurl";

?>