
                <div class="cate-title"><a href="[field:typeurl/]">[field:typename/]</a></div>;
                <!--global $dsql;-->
                <!--$sql="select title from oraimo_archives where id=109";-->
                <!--$recom=$dsql->getOne($dsql);-->
                [field:recom]
                @me="";
                [/field:recom]
            <!--[field:id/]-->
                <!--[field:qupro runphp='yes']-->
                    <!--global $dsql;-->
                  <!--$art3="select title from oraimo_archives where id=109";-->
                  <!--$links=GetOneArchive(109);-->
                  <!--$url=$url['arcurl'];-->
                <!--[/field:qupro]-->
                