<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('78', '/uploads/allimg/150621/1-1506211A5501W.png');
$maNum = 1;
$myaddons[$maNum] = array('79', '/uploads/allimg/150622/1-150622030350E3.jpg');
$maNum = 2;
$myaddons[$maNum] = array('80', '/uploads/allimg/150622/1-150622030439316.jpg');
$maNum = 3;
$myaddons[$maNum] = array('81', '/uploads/allimg/150622/1-150622030450138.jpg');
$maNum = 4;
