<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('106', '/uploads/allimg/150623/1-150623132235c2.png');
$maNum = 1;
$myaddons[$maNum] = array('107', '/uploads/allimg/150623/1-15062313302MH.png');
$maNum = 2;
$myaddons[$maNum] = array('108', '/uploads/allimg/150623/1-150623133FT45.png');
$maNum = 3;
$myaddons[$maNum] = array('109', '/uploads/allimg/150623/1-15062313420H27.png');
$maNum = 4;
$myaddons[$maNum] = array('110', '/uploads/allimg/150623/1-150623134223393.jpg');
$maNum = 5;
$myaddons[$maNum] = array('111', '/uploads/allimg/150623/1-15062313423U03.png');
$maNum = 6;
$myaddons[$maNum] = array('112', '/uploads/allimg/150623/1-150623134JE14.png');
$maNum = 7;
