<?php
$typeArr[1] = 'About Us';
$typeArr[6] = 'Cases';
$typeArr[7] = 'Indoor';
$typeArr[8] = 'Landscape';
$typeArr[12] = 'Services';
$typeArr[13] = 'Design';
$typeArr[18] = 'Consulting';
$typeArr[19] = 'Products';
$typeArr[20] = 'Hand carry';
$typeArr[21] = 'Indoor';
$typeArr[24] = 'News';
$typeArr[26] = 'Industry Information';
$typeArr[27] = 'Company Dynamic';
$typeArr[28] = 'Partners';
$typeArr[29] = 'Join Us';
$typeArr[30] = 'Contact Us';
$typeArr[31] = 'BANNER';
$typeArr[45] = 'Outdoor';
$typeArr[46] = 'Solar';
$typeArr[47] = 'Electrotechnical';
$typeArr[48] = 'Road';
$typeArr[49] = 'After-sales';
?>