<?php
$z[0]=Array("global","",460,481);
$z[0][4]['name']="cfg_qq";
$z[1]=Array("channel","\r\n    | <a href='[field:typelink/]'  class=\"top\">[field:typename/]</a>\r\n    ",704,820);
$z[1][4]['type']="top";
$z[2]=Array("global","",864,890);
$z[2][4]['name']="cfg_banquan";
$z[3]=Array("global","",891,917);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",919,943);
$z[4][4]['name']="cfg_beian";

?>