<?php
$z[0]=Array("field","(@me==\"\")? @me=\"cur\":@me=\"\";",324,402);
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[1]=Array("channelartlist","\r\n      <li> <a href=\"{dede:field name='typeurl'/}\" class=\"z {dede:field.currentstyle/}\">{dede:field name='typename'/}</a>\r\n        <div class=\"nav2\">{dede:channel type='son' noself='yes'}<a href=\"[field:typelink/]\" class=\"[field:global runphp='yes' name=autoindex](@me < 1)?@me=\"no_bg\":@me=\"\";[/field:global] \">[field:typename/]</a>{/dede:channel}</div>\r\n      </li>\r\n      ",428,896);
$z[1][4]['typeid']="1,6,12,19,24,28,29,30";
$z[1][4]['currentstyle']="cur";

?>